[package]
name = "orbit"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Orbital propagation and mechanics for orskit"

[dependencies]
ode_solvers.workspace = true
orskit-core = { path = "../core" }
orskit-units = { path = "../units" }
thiserror.workspace = true
