[package]
name = "dynamics-sgp4"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Fixed-model SGP4 propagation for orskit"

[lib]
name = "dynamics_sgp4"

[dependencies]
dynamics_core = { package = "dynamics-core", path = "../core" }
frames = { path = "../../frames" }
hifitime.workspace = true
orskit_core = { package = "core", path = "../../core" }
orbits = { path = "../../orbits", features = ["cartesian"] }
sgp4.workspace = true
thiserror.workspace = true
units = { path = "../../units" }
