[package]
name = "utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Utility functions and helpers for orskit"

[lib]
name = "utils"

[dependencies]
units = { path = "../units" }
