[package]
name = "dynamics-numerical"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Adaptive translational Cartesian propagation for orskit"

[lib]
name = "dynamics_numerical"

[dependencies]
dynamics_core = { package = "dynamics-core", path = "../core" }
frames = { path = "../../frames" }
hifitime.workspace = true
orskit_core = { package = "core", path = "../../core" }
orbits = { path = "../../orbits", features = ["cartesian"] }
thiserror.workspace = true
units = { path = "../../units" }

[dev-dependencies]
bodies = { path = "../../bodies" }
dynamics_two_bodies = { package = "dynamics-two-bodies", path = "../two-bodies", features = ["point-mass"] }
gravity = { path = "../../gravity", features = ["point-mass"] }
