[package]
name = "gravity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Point-mass gravity selection implementation for orskit"

[lib]
name = "gravity"

[features]
default = []
point-mass = []
zonal = ["dep:thiserror"]

[dependencies]
frames = { path = "../frames" }
thiserror = { workspace = true, optional = true }
units = { path = "../units" }
