[package]
name = "orskit-measurements"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Measurement and observation utilities for orskit"

[dependencies]
hifitime.workspace = true
orskit-frames = { path = "../frames" }
orskit-units = { path = "../units" }
thiserror.workspace = true
