[package]
name = "measurements"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Measurement and observation utilities for orskit"

[lib]
name = "measurements"

[dependencies]
hifitime.workspace = true
frames = { path = "../frames" }
units = { path = "../units" }
thiserror.workspace = true
