[package]
name = "orskit-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core orbital mechanics library for orskit"

[dependencies]
hifitime.workspace = true
nalgebra.workspace = true
orskit-frames = { path = "../frames" }
orskit-units = { path = "../units" }
thiserror.workspace = true
