[package]
name = "orskit-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core orbital mechanics library for orskit"

[lib]
name = "orskit_core"

[dependencies]
hifitime.workspace = true
nalgebra.workspace = true
frames = { package = "orskit-frames", path = "../frames" }
units = { package = "orskit-units", path = "../units" }
thiserror.workspace = true
