[package]
name = "orskit-gravity-point-mass"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Point-mass gravity selection implementation for orskit"

[lib]
name = "gravity_point_mass"

[dependencies]
core_crate = { package = "orskit-core", path = "../core" }
frames = { package = "orskit-frames", path = "../frames" }
thiserror.workspace = true
units = { package = "orskit-units", path = "../units" }
