[package]
name = "tle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Strict Two-Line Element parsing and formatting for orskit"

[features]
default = []
sgp4 = [
    "dep:dynamics",
    "dep:hifitime",
    "dep:orskit_core",
    "dep:units",
]

[dependencies]
dynamics = { path = "../dynamics", features = ["sgp4"], optional = true }
hifitime = { workspace = true, optional = true }
orskit_core = { package = "core", path = "../core", optional = true }
thiserror.workspace = true
units = { path = "../units", optional = true }
